pr:
  autoCancel: 'false'
  branches:
    include:
      - main
      - develop

trigger:
  branches:
    include:
      - main
      - develop

variables:
- template: .pipelines/variables/project.yml
- template: .pipelines/variables/connections.yml

stages:
  - stage: CI_build
    displayName: Build artifact
    jobs:
      - template: .pipelines/templates/ci.build.job.yml
        parameters:
          artifactName: 'artifact'

      - template: .pipelines/templates/ci.lint.job.yml
        parameters:
          dependsOn: 'build_artifact'
          artifactName: 'artifact'


  - stage: CI_smoke_test
    dependsOn: CI_build
    displayName: Smoke tests
    condition: and(
        succeeded(),
        or(
          startsWith(variables['Build.SourceBranch'], 'refs/heads/main'),
          startsWith(variables['Build.SourceBranch'], 'refs/heads/develop'),
          startsWith(variables['Build.SourceBranch'], 'refs/pull/')
        )
      )
    jobs:
      - template: .pipelines/templates/ci.smoke.test.job.yml
        parameters:
          neededArtifacts:
            - 'artifact'
            - 'infrastructure'
          azureConnection: $(azureConnectionName)
          configKeyVault: $(configKeyVault)
          artifactName: 'artifact'


  - stage: E2E
    dependsOn: CI_smoke_test
    displayName: Deploy config and run end to end tests
    condition: and(
        succeeded(),
        or(
          startsWith(variables['Build.SourceBranch'], 'refs/heads/main'),
          startsWith(variables['Build.SourceBranch'], 'refs/heads/develop'),
          startsWith(variables['Build.SourceBranch'], 'refs/pull/')
        )
      )
    jobs:
      - template: .pipelines/templates/e2e.prepare.tests.job.yml
        parameters:
          neededArtifacts:
            - 'artifact'

      - template: .pipelines/templates/e2e.execute.tests.job.yml
        parameters:
          dependsOn: 'deploy_e2e_infra'


  - stage: CD
    displayName: Update repositories
    dependsOn: E2E
    condition: and(
        succeeded(),
        eq(variables['Build.SourceBranch'], 'refs/heads/main')
      )
    jobs:
      - template: templates/cd.push.git.job.yml@templates
        parameters:
          repository: 'publicRepo'
          neededArtifacts:
            - 'artifact'
          artifactName: 'artifact'
          environment: 'prod'
          targetBranch: 'feature/update-aws'
          branchName: 'feature/test'
          relativeFolderPath: 'AWS'
          gitUserEmail: '$(gitUserEmail)'
          gitUserHandle: '$(gitUserHandle)'

      - template: templates/cd.push.git.job.yml@templates
        parameters:
          repository: 'privateFork'
          neededArtifacts:
            - 'artifact'
          artifactName: 'artifact'
          environment: 'remote'
          targetBranch: 'feature/update-aws'
          branchName: 'feature/test'
          relativeFolderPath: 'AWS'
          gitUserEmail: '$(gitUserEmail)'
          gitUserHandle: '$(gitUserHandle)'


resources:
  repositories:
    - repository: templates
      type: github
      endpoint: UiPath
      name: UiPath/cloud-marketplace-common
    - repository: publicRepo
      type: github
      endpoint: UiPath
      name: UiPath/Infrastructure
      ref: main
    - repository: privateFork
      type: github
      endpoint: AndreiBarbuOz
      name: AndreiBarbuOz/quickstart-uipath-robot
      ref: main
